import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import CommonCheckoutLayout from "@/components/Checkout/common/CommonCheckoutLayout";
import "../globals.css"
import { Toaster } from "@/components/ui/sonner"

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Welcome to Nexus_Grocery",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <CommonCheckoutLayout>{children}</CommonCheckoutLayout>
        <Toaster />

      </body>
    </html>
  );
}
